### ISSUE TITLE
If i copy from results then nagative promts get copied in normal promts section after ###

### ISSUE THREAD

**Issue by BigDogg99** [daveschumaker/artbot-for-stable-diffusion#1]
title and i am using it on mobile

**Comment by daveschumaker** [comment]
Thanks for reporting this! I had just noticed it myself as well and deployed a fix about 15 minutes ago: 953dff73644733d3a2395c88e

It should now be live and the issue should be resolved.

**Comment by BigDogg99** [comment]
thanks for your work
