### ISSUE TITLE
Retrying stuck job defaults to stable_diffusion model

### ISSUE THREAD

**Issue by danupton** [daveschumaker/artbot-for-stable-diffusion#11]
I was trying out the new "use all models" feature this morning and had 3-4 pop up with the "job appears to be stuck" error. Clicking the retry button defaults back to stable_diffusion model instead of whatever the job was actually running. This isn't a huge deal if no seed was supplied, but it's a little inefficient when trying to explore all models for a given seed and it ends up having multiple workers run identical settings.

**Comment by daveschumaker** [comment]
Ah! That's a good one. I'll take a look. Thanks!

**Comment by daveschumaker** [comment]
Alright, I believe I have fixed this (I haven't really been able to reproduce it on my end, but I think I know where it's been happening). I'm going to close this ticket out, but let me know if you still encounter it!
