### ISSUE TITLE
Feature request: Option to not switch to the Pending Tab

### ISSUE THREAD

**Issue by KyuubiYoru** [daveschumaker/artbot-for-stable-diffusion#14]
I would like an option to not automatically switch to the Pending tab when I click Create.

**Comment by daveschumaker** [comment]
Thanks for the suggestion!

I'm trying to think about this from a user experience and user interface perspective: 
* What should happen after clicking "create"? Some sort of toast should pop up that says "image requested"?
* Should all the input fields clear out and you start fresh? If not how would you want to know that your request was successfully sent?

**Comment by KyuubiYoru** [comment]
1. Nothing that requires my interaction or blocks my interaction, I would find it annoying if a pop-up appeared and I had to click OK, perhaps the Pending Tab flashing or a "image requested" flashing and disappearing could work.

2. The fields should typically retain their values, typically, I want to experiment with the parameters and only want to change one at a time, keeping the other values the same.

My typical workflow is to request multiple sets of images with varying parameters and then compare them.

**Comment by daveschumaker** [comment]
Still thinking about this. There's some error handling issues I'm working on related to image requests in general. Once I get those hammered out, I can revisit this.

**Comment by daveschumaker** [comment]
This has now been implemented. You can enable the option here:
https://tinybots.net/artbot/settings?panel=prefs

Thanks for the suggestion.
