### ISSUE TITLE
Use all models / Multi-model select

### ISSUE THREAD

**Issue by Abul22** [daveschumaker/artbot-for-stable-diffusion#15]
1 bug I think and 1 feature req

For use all models -- I think this has broken in the last few days? When using only getting 1 single generation, despite (43) models showing.

For multi model select -- It would be great if it didn't collapse after selecting each time. ( also I think after this generates the multi model checkbox y/n isn't preserved like other settings, when that is on)

An awesome interface for sure tho! Cheers

**Comment by daveschumaker** [comment]
Thanks for reporting this. The all models feature has been fixed. 

I’ve also added the ability for multi-model select to stay open. It's working on desktop but not on mobile devices. 🤔

I'll leave this issue open as I continue to investigate.
