### ISSUE TITLE
Bug: Model SDXL: Losing Picture #1 when chosing Picture #2 as favourite when saving

### ISSUE THREAD

**Issue by LastZolex** [daveschumaker/artbot-for-stable-diffusion#155]
I just realized that on SDXL renderings, when I have chosen the second image as my favourite, two images are stored as expected, but it is the second picture that is stored twice. The first picture is lost.

If I have chosen the first picture as my favourite, then the first and the second picture are stored, which is fine ;)

After testing this a little bit further, I guess (without looking at the code) that the procedure is like this:

1. save both SDXL images (is done automatically now)
2. let the user vote to improve the model (as usual)
3. store the chosen picture again, overwriting the first pic

step 3 might be not needed anymore...

**Comment by daveschumaker** [comment]
Thank you for reporting this! I believe this should now be fixed as of PR #175

**Comment by LastZolex** [comment]
yes, indeed it was elegantly fixed by you ;) I love the new way of choice you offer! Great work! :)
