### ISSUE TITLE
"Number of images" is incorrect.

### ISSUE THREAD

**Issue by KyuubiYoru** [daveschumaker/artbot-for-stable-diffusion#16]
It appears that "Number of images" times "Number of images" gets requested.

**Comment by daveschumaker** [comment]
Thank you! Will have a fix for this shortly.

**Comment by daveschumaker** [comment]
Fixed. Thanks again!

**Comment by nerdCopter** [comment]
possibly still broken.  i set 5, but 47 queued.

**Comment by daveschumaker** [comment]
> possibly still broken. i set 5, but 47 queued.

Hmm, I'm seeing the following bug:

1. Generate a whole bunch of images. Go view one. Go back to create page and create a new batch of images (e.g., 5)
2. When automatically redirected to the images page, I see all the finished images from my previous request, as well as the new pending images, so it ends up showing like 20+ images under "All".

Does this track with what you're seeing or is it something totally different?

**Comment by nerdCopter** [comment]
i've run multiple art-bot sessions from same firefox session. it may be tracking or adding image-count. it's hard to troubleshoot.  i did open a second tab, but realized it did not sandbox the session, so i closed the tab.
one time i did notice a handful of images did not pertain to my text-input at all, but followed up with images that did (in the same processing session).  seems to be some cross-contamination somewhere.

**Comment by nerdCopter** [comment]
i believe this can be closed.  i'm no longer witnessing the issue.

**Comment by daveschumaker** [comment]
Thank you!
