### ISSUE TITLE
Ad container appears to be blocking links in sidebar

### ISSUE THREAD

**Issue by daveschumaker** [daveschumaker/artbot-for-stable-diffusion#168]
![artbot_ad](https://github.com/daveschumaker/artbot-for-stable-diffusion/assets/5395723/7dd27936-7eb8-44e3-b857-e097d96ac9b5)

**Comment by LastZolex** [comment]
...and sometimes the ads get "out of hands" ;) 

unfortunately my company's rules disallow uploading any binaries to github, but you (hopefully) can see what I mean here:
https://ibb.co/YBfL5GS

I am not sure if these issues are somehow related or if it is worth another bug ticket.
