### ISSUE TITLE
request for better filename ( "save-as" and/or download-PNG )

### ISSUE THREAD

**Issue by nerdCopter** [daveschumaker/artbot-for-stable-diffusion#17]
when performing save-as (save image as), generic filename of `index.webp`  or `download.webp` is used. 
when clicking "[ download PNG ]" it simply uses the generation text.

It may be useful to re-use some hash or job id in addition to the generation text.
e.g. 
* https://tinybots.net/artbot/image/a46223b9-c732-4db1-88db-1441b6b01070 ---> i_don_t_like_batteries_in_my_ears_a46223b9-c732-4db1-88db-1441b6b01070.png

thanks for the awesomeness!!

**Comment by daveschumaker** [comment]
Sorry for the thread necromancy here, but I've done some digging and it looks like it isn't possible for me to set a default name when you right click -> save as in the browser. More info:
https://stackoverflow.com/questions/37859069/how-to-change-save-image-to-file-default-name

The hacky alternative / workaround is that if you click the "download" option on the image details page (in the toolbar beneath the image), this is able to set a default name via JavaScript that the browser can then download.
