### ISSUE TITLE
SDXL not working as expected (a "due to heavy load"-variant)

### ISSUE THREAD

**Issue by LastZolex** [daveschumaker/artbot-for-stable-diffusion#206]
Hi there,
today I tried the SDXL model after a while and realized that I constantly get the well known message "Stable Horde API Error: "Due to heavy demand, for requests over 1266x1266 or over 50 steps (25 for k_heun and k_dpm_2*), the client needs to already have the required kudos."

So far, so expected if I was using any parameters beyond the noted thresholds, but I do not.
My current request configs are
Size: 1024x1024 -> no upscaling
Sampler: k_euler_a
Steps: 20
No post-processing
No Upscalers
No additional options

if I use exactly these parameters with the same prompt on another Stable Horde webUI I get a picture generated. 
Is this a bug, or am I doing something wrong?

**Comment by Efreak** [comment]
Try resetting input cache in [ArtBot settings](https://tinybots.net/artbot/settings?panel=prefs), there's an occasional glitch that hasn't been tracked down yet that makes things stick.

Free Kudos: 
- Join the discord if possible, posting images is a good way to get free kudos (we like seeing nice stuff)
- you can get less kudos by rating images
- you can get more kudos by running a worker yourself. If you don't have a local GPU, you can use Kaggle or Google Colab or possibly Paperspace gradient for free, or paid hosting with runpod and vast. You can get help with this in the [discord server](https://discord.com/invite/2TprSJjSxg).
- Counterflow on discord has offered up a free shared key with ~3 million kudos left on it, this should be plenty for a while. You can use it with [this link](https://tinybots.net/artbot?shared_key=1fcff7c5-eb3d-4eb7-99f0-08d4a78457f6) (please try resetting the input cache first before using this key, and report back if it doesn't actually work).
- there's free themed generation parties pretty much constantly on discord these days. The only requirement is logging in via discord. If nobody else is running a party, it's usually me (currently I'm running 5!). The party creator usually not only pays for the generation itself, you get faster results and often receive kudos for each generation.

**Comment by LastZolex** [comment]
Thanks a lot, this is the one thing I had not tried ;) ;)

I have currently spent my all riches (aka piles of Kudos), but I promise to gather fresh ones next year!
The thing about Discord parties is definitely new to me ;)
