### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by khanfar** [daveschumaker/artbot-for-stable-diffusion#22]
hi , i download the zip source and try this  npm run dev then got this error : 
> next-horde@0.1.0 dev
> npm run update:build-id && PORT=3000 node server.js

> next-horde@0.1.0 update:build-id
> node ./x-build-scripts/updateBuildId.js

'PORT' is not recognized as an internal or external command,
operable program or batch file.

please help

**Comment by daveschumaker** [comment]
This sounds like an issue when running on Windows. Please see this part of the FAQ:
https://github.com/daveschumaker/artbot-for-stable-diffusion#windows-issues
