### ISSUE TITLE
Enhancement: Add Adetailer

### ISSUE THREAD

**Issue by metapea** [daveschumaker/artbot-for-stable-diffusion#221]
Add the webui extension [Adetailer](https://github.com/Bing-su/adetailer) to artbot

**Comment by Efreak** [comment]
ArtBot is just an interface to the [AI Horde](https://aihorde.net)'s image generation service. In order to add features like this to ArtBot, they need to first be added to Horde. You can request this at [Haidra-Org](https://github.com/Haidra-Org/AI-Horde).

**Comment by metapea** [comment]
Aright, i thought Adetailer was an extension more on the users end since there was already option like "GFPGAN". But i'm guessing now, "GFPGAN" is there because [AI Horde](https://aihorde.net/) already supports a few "Post-processing" options to use
