### ISSUE TITLE
suggestions to make site more better

### ISSUE THREAD

**Issue by BigDogg99** [daveschumaker/artbot-for-stable-diffusion#3]
1.add diffrent tab for inpainting
2.advanced option opened by default or a option to enable it
3.option to put custom  Image orientation

**Comment by daveschumaker** [comment]
Thanks for the suggestion. I broke your requests out into a number of sub-features and I'll start working on them soon. I'll leave this issue open until I am able to complete each request.

**Comment by daveschumaker** [comment]
I have completed all 3 feature requests. Let me know if you have any other ideas. Thank you!
