### ISSUE TITLE
UX: Contradicting key bindings in gallery browsing

### ISSUE THREAD

**Issue by LastZolex** [daveschumaker/artbot-for-stable-diffusion#41]
switching through the pictures of the gallery can be done by clicking on the left/right arrows beside the picture or by pressing the left/right arrow key on the keyboard.

UI Buttons clicking:
- clicking on the left navigational arrow button leads to the next older picture.
- clicking on the right navigational arrow button leads to the next newer picture.

Keyboard key press:
- pressing the left arrow key leads to the next newer picture
- pressing the right arrow key leads to the next older picture

so at least to me, these navigational alternative feel contradicting to me ;)

**Comment by daveschumaker** [comment]
Ah, yes. That makes sense. Thanks for reporting. I'll take a look!

**Comment by LastZolex** [comment]
works perfectly now, thanks a lot :)
