### ISSUE TITLE
UX: dead gallery browsing dialog when browsing back beyond the first picture

### ISSUE THREAD

**Issue by LastZolex** [daveschumaker/artbot-for-stable-diffusion#42]
when browsing through the gallery, either by clicking on the ui button or using the keyboard keys, everytime when I am at the first picture of my gallery and navigate one picture back in time to a picture that of course does not exist, the browsing dialog gets empty and is stuck there. navigationg to the first picture is no longer possible.

the situation can be remedied by closing the browsing dialog and starting over again.

In my gallery this is reproducible 100% of the time.

Maybe it is helpful to know, that I already deleted pictures from the gallery using the provided web ui, so I guess the original "first picture" is not available anymore. this may or may not help in finding the cause. maybe it is just an "off by one" in the boundaries check ;)

**Comment by daveschumaker** [comment]
Thanks for reporting this!

**Comment by evguu** [comment]
https://github.com/daveschumaker/artbot-for-stable-diffusion/blob/main/pages/images.tsx

line 238

shouldn't it be >= ?
