### ISSUE TITLE
Standardize error messages on Create Page.

### ISSUE THREAD

**Issue by daveschumaker** [daveschumaker/artbot-for-stable-diffusion#70]
I like this idea of creating an specific error component. This particular feedback is more for me, but those props make me think that I should really standardize the error messages the web app is generating. Will add to the to-do list and definitely not a blocker for the PR.

_Originally posted by @daveschumaker in https://github.com/daveschumaker/artbot-for-stable-diffusion/pull/67#discussion_r1140790185_

**Comment by evguu** [comment]
Would be great if it allowed to show multiple errors at once

**Comment by evguu** [comment]
Progress towards this issue by #87

**Comment by evguu** [comment]
Progress towards this issue by #88 and #90
