### ISSUE TITLE
Feature: Maintain aspect ratio when changing sizes

### ISSUE THREAD

**Issue by daveschumaker** [daveschumaker/artbot-for-stable-diffusion#72]
This is probably hard to implement, given all image sizes need to be a multiple of 64 pixels, but it'd be nice to figure out a way to optionally

![Image](https://user-images.githubusercontent.com/5395723/226068931-d8555c00-452d-4c77-be7c-11c68bda38ff.jpg)

 "lock" the aspect ratio of an image and dynamically update sizes if possible.

**Comment by evguu** [comment]
close this already :laughing:
