### ISSUE TITLE
Stable Horde API error when using sampler k_heun and more than 50 steps

### ISSUE THREAD

**Issue by david-j-smith** [daveschumaker/artbot-for-stable-diffusion#9]
When I use the Sampler k_heun and the parameter Steps is greater than 50, e.g. 60, I get the following error:
`Error: Stable Horde API error: For requests over 1024x1024 or over 100 steps, the client needs to already have the required kudos. This request requires 25.98 kudos to fulfil.`

When another Sampler is used or the parameter Steps is 50 (or less), everything works as intended.

The Image orientation is square, all created .webp images are 512 x 512.

Thank you very much for this fine piece of software and your time reading this!

**Comment by daveschumaker** [comment]
Thanks for reporting this. It looks like the Stable Horde back end implemented a token system (called "kudos" for more expensive operations (in terms of GPU computing power). 

On the front-end ArtBot side of things, I can add some better messaging related to this and better handle / prevent these sorts of errors in the first place (e.g., limit steps to max of 50 if user is not logged in and doesn't have enough kudos in there account).

Hopefully these sorts of things will be relaxed for anonymous users in the future (potentially as more workers are added to the Stable Horde cluster). db0, the creator of Stable Horde, has a primer on [what the kudos system is](https://dbzer0.com/blog/the-kudos-based-economy-for-the-koboldai-horde/). Essentially, you can earn kudos by donating GPU power (or participating in the community Discord).

**Comment by daveschumaker** [comment]
Alright, I added some better validation handling within the advanced options panel, so you'll get immediate feedback if a parameter is out of range (also, I made the ranges visible in the first place, no more guessing!)

Thanks for letting me know about this.
